---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r}
datos = read.csv("datos_clase_clustering.csv", stringsAsFactors = FALSE)
head(datos)
```

```{r}
datos = datos[!is.na(datos$surface_covered) & !is.na(datos$price),]

datos$ppm = ifelse(datos$surface_covered > 0, datos$price / datos$surface_covered, 0)
```

```{r}
normalizar = function(vec){
  return((vec - min(vec)) / (max(vec) - min(vec)))
}

ppm_norm = normalizar(datos$ppm)
plot(lat ~ lon, data = datos, col = rgb(ppm_norm, 0, 1 - ppm_norm))
```

```{r}
kms_pos = kmeans(datos[, c("lat", "lon")], 3)
col_pos = rainbow(3); names(col_pos) = 1:3

kms_tri = kmeans(datos[, c("ppm", "surface_covered", "price")], 3)
col_tri = rainbow(3); names(col_tri) = 1:3 

par(mfrow = c(1,2))
plot(lat ~ lon, data = datos, col =  col_pos[kms_pos$cluster])
points(x = kms_pos$centers[, "lon"], y = kms_pos$centers[, "lat"], pch = 18)

plot(price ~ surface_covered, data = datos, col = col_tri[kms_tri$cluster])
points(x = kms_tri$centers[, "surface_covered"], y = kms_tri$centers[, "price"], pch = 18)
```

